import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from functools import partial


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(323, 370)
        MainWindow.setMinimumSize(QtCore.QSize(323, 370))
        MainWindow.setMaximumSize(QtCore.QSize(323, 370))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 261, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setStyleSheet("background-color : black")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.led_1 = QtWidgets.QPushButton(self.frame)
        self.led_1.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.led_1.setStyleSheet("background-color : white")
        self.led_1.setText("")
        self.led_1.setObjectName("led_1")
        self.led_2 = QtWidgets.QPushButton(self.frame)
        self.led_2.setGeometry(QtCore.QRect(40, 10, 25, 25))
        self.led_2.setStyleSheet("background-color : white")
        self.led_2.setText("")
        self.led_2.setObjectName("led_2")
        self.led_3 = QtWidgets.QPushButton(self.frame)
        self.led_3.setGeometry(QtCore.QRect(70, 10, 25, 25))
        self.led_3.setStyleSheet("background-color : white")
        self.led_3.setText("")
        self.led_3.setObjectName("led_3")
        self.led_4 = QtWidgets.QPushButton(self.frame)
        self.led_4.setGeometry(QtCore.QRect(100, 10, 25, 25))
        self.led_4.setStyleSheet("background-color : white")
        self.led_4.setText("")
        self.led_4.setObjectName("led_4")
        self.led_5 = QtWidgets.QPushButton(self.frame)
        self.led_5.setGeometry(QtCore.QRect(130, 10, 25, 25))
        self.led_5.setStyleSheet("background-color : white")
        self.led_5.setText("")
        self.led_5.setObjectName("led_5")
        self.led_6 = QtWidgets.QPushButton(self.frame)
        self.led_6.setGeometry(QtCore.QRect(160, 10, 25, 25))
        self.led_6.setStyleSheet("background-color : white")
        self.led_6.setText("")
        self.led_6.setObjectName("led_6")
        self.led_7 = QtWidgets.QPushButton(self.frame)
        self.led_7.setGeometry(QtCore.QRect(190, 10, 25, 25))
        self.led_7.setStyleSheet("background-color : white")
        self.led_7.setText("")
        self.led_7.setObjectName("led_7")
        self.led_8 = QtWidgets.QPushButton(self.frame)
        self.led_8.setGeometry(QtCore.QRect(220, 10, 25, 25))
        self.led_8.setStyleSheet("background-color : white")
        self.led_8.setText("")
        self.led_8.setObjectName("led_8")
        self.led_9 = QtWidgets.QPushButton(self.frame)
        self.led_9.setGeometry(QtCore.QRect(10, 40, 25, 25))
        self.led_9.setStyleSheet("background-color : white")
        self.led_9.setText("")
        self.led_9.setObjectName("led_9")
        self.led_10 = QtWidgets.QPushButton(self.frame)
        self.led_10.setGeometry(QtCore.QRect(40, 40, 25, 25))
        self.led_10.setStyleSheet("background-color : white")
        self.led_10.setText("")
        self.led_10.setObjectName("led_10")
        self.led_11 = QtWidgets.QPushButton(self.frame)
        self.led_11.setGeometry(QtCore.QRect(70, 40, 25, 25))
        self.led_11.setStyleSheet("background-color : white")
        self.led_11.setText("")
        self.led_11.setObjectName("led_11")
        self.led_12 = QtWidgets.QPushButton(self.frame)
        self.led_12.setGeometry(QtCore.QRect(100, 40, 25, 25))
        self.led_12.setStyleSheet("background-color : white")
        self.led_12.setText("")
        self.led_12.setObjectName("led_12")
        self.led_13 = QtWidgets.QPushButton(self.frame)
        self.led_13.setGeometry(QtCore.QRect(130, 40, 25, 25))
        self.led_13.setStyleSheet("background-color : white")
        self.led_13.setText("")
        self.led_13.setObjectName("led_13")
        self.led_14 = QtWidgets.QPushButton(self.frame)
        self.led_14.setGeometry(QtCore.QRect(160, 40, 25, 25))
        self.led_14.setStyleSheet("background-color : white")
        self.led_14.setText("")
        self.led_14.setObjectName("led_14")
        self.led_15 = QtWidgets.QPushButton(self.frame)
        self.led_15.setGeometry(QtCore.QRect(190, 40, 25, 25))
        self.led_15.setStyleSheet("background-color : white")
        self.led_15.setText("")
        self.led_15.setObjectName("led_15")
        self.led_16 = QtWidgets.QPushButton(self.frame)
        self.led_16.setGeometry(QtCore.QRect(220, 40, 25, 25))
        self.led_16.setStyleSheet("background-color : white")
        self.led_16.setText("")
        self.led_16.setObjectName("led_16")
        self.led_17 = QtWidgets.QPushButton(self.frame)
        self.led_17.setGeometry(QtCore.QRect(10, 70, 25, 25))
        self.led_17.setStyleSheet("background-color : white")
        self.led_17.setText("")
        self.led_17.setObjectName("led_17")
        self.led_18 = QtWidgets.QPushButton(self.frame)
        self.led_18.setGeometry(QtCore.QRect(40, 70, 25, 25))
        self.led_18.setStyleSheet("background-color : white")
        self.led_18.setText("")
        self.led_18.setObjectName("led_18")
        self.led_19 = QtWidgets.QPushButton(self.frame)
        self.led_19.setGeometry(QtCore.QRect(70, 70, 25, 25))
        self.led_19.setStyleSheet("background-color : white")
        self.led_19.setText("")
        self.led_19.setObjectName("led_19")
        self.led_20 = QtWidgets.QPushButton(self.frame)
        self.led_20.setGeometry(QtCore.QRect(100, 70, 25, 25))
        self.led_20.setStyleSheet("background-color : white")
        self.led_20.setText("")
        self.led_20.setObjectName("led_20")
        self.led_21 = QtWidgets.QPushButton(self.frame)
        self.led_21.setGeometry(QtCore.QRect(130, 70, 25, 25))
        self.led_21.setStyleSheet("background-color : white")
        self.led_21.setText("")
        self.led_21.setObjectName("led_21")
        self.led_22 = QtWidgets.QPushButton(self.frame)
        self.led_22.setGeometry(QtCore.QRect(160, 70, 25, 25))
        self.led_22.setStyleSheet("background-color : white")
        self.led_22.setText("")
        self.led_22.setObjectName("led_22")
        self.led_23 = QtWidgets.QPushButton(self.frame)
        self.led_23.setGeometry(QtCore.QRect(190, 70, 25, 25))
        self.led_23.setStyleSheet("background-color : white")
        self.led_23.setText("")
        self.led_23.setObjectName("led_23")
        self.led_24 = QtWidgets.QPushButton(self.frame)
        self.led_24.setGeometry(QtCore.QRect(220, 70, 25, 25))
        self.led_24.setStyleSheet("background-color : white")
        self.led_24.setText("")
        self.led_24.setObjectName("led_24")
        self.led_25 = QtWidgets.QPushButton(self.frame)
        self.led_25.setGeometry(QtCore.QRect(10, 100, 25, 25))
        self.led_25.setStyleSheet("background-color : white")
        self.led_25.setText("")
        self.led_25.setObjectName("led_25")
        self.led_26 = QtWidgets.QPushButton(self.frame)
        self.led_26.setGeometry(QtCore.QRect(40, 100, 25, 25))
        self.led_26.setStyleSheet("background-color : white")
        self.led_26.setText("")
        self.led_26.setObjectName("led_26")
        self.led_27 = QtWidgets.QPushButton(self.frame)
        self.led_27.setGeometry(QtCore.QRect(70, 100, 25, 25))
        self.led_27.setStyleSheet("background-color : white")
        self.led_27.setText("")
        self.led_27.setObjectName("led_27")
        self.led_28 = QtWidgets.QPushButton(self.frame)
        self.led_28.setGeometry(QtCore.QRect(100, 100, 25, 25))
        self.led_28.setStyleSheet("background-color : white")
        self.led_28.setText("")
        self.led_28.setObjectName("led_28")
        self.led_29 = QtWidgets.QPushButton(self.frame)
        self.led_29.setGeometry(QtCore.QRect(130, 100, 25, 25))
        self.led_29.setStyleSheet("background-color : white")
        self.led_29.setText("")
        self.led_29.setObjectName("led_29")
        self.led_30 = QtWidgets.QPushButton(self.frame)
        self.led_30.setGeometry(QtCore.QRect(160, 100, 25, 25))
        self.led_30.setStyleSheet("background-color : white")
        self.led_30.setText("")
        self.led_30.setObjectName("led_30")
        self.led_31 = QtWidgets.QPushButton(self.frame)
        self.led_31.setGeometry(QtCore.QRect(190, 100, 25, 25))
        self.led_31.setStyleSheet("background-color : white")
        self.led_31.setText("")
        self.led_31.setObjectName("led_31")
        self.led_32 = QtWidgets.QPushButton(self.frame)
        self.led_32.setGeometry(QtCore.QRect(220, 100, 25, 25))
        self.led_32.setStyleSheet("background-color : white")
        self.led_32.setText("")
        self.led_32.setObjectName("led_32")
        self.led_33 = QtWidgets.QPushButton(self.frame)
        self.led_33.setGeometry(QtCore.QRect(10, 130, 25, 25))
        self.led_33.setStyleSheet("background-color : white")
        self.led_33.setText("")
        self.led_33.setObjectName("led_33")
        self.led_34 = QtWidgets.QPushButton(self.frame)
        self.led_34.setGeometry(QtCore.QRect(40, 130, 25, 25))
        self.led_34.setStyleSheet("background-color : white")
        self.led_34.setText("")
        self.led_34.setObjectName("led_34")
        self.led_35 = QtWidgets.QPushButton(self.frame)
        self.led_35.setGeometry(QtCore.QRect(70, 130, 25, 25))
        self.led_35.setStyleSheet("background-color : white")
        self.led_35.setText("")
        self.led_35.setObjectName("led_35")
        self.led_36 = QtWidgets.QPushButton(self.frame)
        self.led_36.setGeometry(QtCore.QRect(100, 130, 25, 25))
        self.led_36.setStyleSheet("background-color : white")
        self.led_36.setText("")
        self.led_36.setObjectName("led_36")
        self.led_37 = QtWidgets.QPushButton(self.frame)
        self.led_37.setGeometry(QtCore.QRect(130, 130, 25, 25))
        self.led_37.setStyleSheet("background-color : white")
        self.led_37.setText("")
        self.led_37.setObjectName("led_37")
        self.led_38 = QtWidgets.QPushButton(self.frame)
        self.led_38.setGeometry(QtCore.QRect(160, 130, 25, 25))
        self.led_38.setStyleSheet("background-color : white")
        self.led_38.setText("")
        self.led_38.setObjectName("led_38")
        self.led_39 = QtWidgets.QPushButton(self.frame)
        self.led_39.setGeometry(QtCore.QRect(190, 130, 25, 25))
        self.led_39.setStyleSheet("background-color : white")
        self.led_39.setText("")
        self.led_39.setObjectName("led_39")
        self.led_40 = QtWidgets.QPushButton(self.frame)
        self.led_40.setGeometry(QtCore.QRect(220, 130, 25, 25))
        self.led_40.setStyleSheet("background-color : white")
        self.led_40.setText("")
        self.led_40.setObjectName("led_40")
        self.led_41 = QtWidgets.QPushButton(self.frame)
        self.led_41.setGeometry(QtCore.QRect(10, 160, 25, 25))
        self.led_41.setStyleSheet("background-color : white")
        self.led_41.setText("")
        self.led_41.setObjectName("led_41")
        self.led_42 = QtWidgets.QPushButton(self.frame)
        self.led_42.setGeometry(QtCore.QRect(40, 160, 25, 25))
        self.led_42.setStyleSheet("background-color : white")
        self.led_42.setText("")
        self.led_42.setObjectName("led_42")
        self.led_43 = QtWidgets.QPushButton(self.frame)
        self.led_43.setGeometry(QtCore.QRect(70, 160, 25, 25))
        self.led_43.setStyleSheet("background-color : white")
        self.led_43.setText("")
        self.led_43.setObjectName("led_43")
        self.led_44 = QtWidgets.QPushButton(self.frame)
        self.led_44.setGeometry(QtCore.QRect(100, 160, 25, 25))
        self.led_44.setStyleSheet("background-color : white")
        self.led_44.setText("")
        self.led_44.setObjectName("led_44")
        self.led_45 = QtWidgets.QPushButton(self.frame)
        self.led_45.setGeometry(QtCore.QRect(130, 160, 25, 25))
        self.led_45.setStyleSheet("background-color : white")
        self.led_45.setText("")
        self.led_45.setObjectName("led_45")
        self.led_46 = QtWidgets.QPushButton(self.frame)
        self.led_46.setGeometry(QtCore.QRect(160, 160, 25, 25))
        self.led_46.setStyleSheet("background-color : white")
        self.led_46.setText("")
        self.led_46.setObjectName("led_46")
        self.led_47 = QtWidgets.QPushButton(self.frame)
        self.led_47.setGeometry(QtCore.QRect(190, 160, 25, 25))
        self.led_47.setStyleSheet("background-color : white")
        self.led_47.setText("")
        self.led_47.setObjectName("led_47")
        self.led_48 = QtWidgets.QPushButton(self.frame)
        self.led_48.setGeometry(QtCore.QRect(220, 160, 25, 25))
        self.led_48.setStyleSheet("background-color : white")
        self.led_48.setText("")
        self.led_48.setObjectName("led_48")
        self.led_49 = QtWidgets.QPushButton(self.frame)
        self.led_49.setGeometry(QtCore.QRect(10, 190, 25, 25))
        self.led_49.setStyleSheet("background-color : white")
        self.led_49.setText("")
        self.led_49.setObjectName("led_49")
        self.led_50 = QtWidgets.QPushButton(self.frame)
        self.led_50.setGeometry(QtCore.QRect(40, 190, 25, 25))
        self.led_50.setStyleSheet("background-color : white")
        self.led_50.setText("")
        self.led_50.setObjectName("led_50")
        self.led_51 = QtWidgets.QPushButton(self.frame)
        self.led_51.setGeometry(QtCore.QRect(70, 190, 25, 25))
        self.led_51.setStyleSheet("background-color : white")
        self.led_51.setText("")
        self.led_51.setObjectName("led_51")
        self.led_52 = QtWidgets.QPushButton(self.frame)
        self.led_52.setGeometry(QtCore.QRect(100, 190, 25, 25))
        self.led_52.setStyleSheet("background-color : white")
        self.led_52.setText("")
        self.led_52.setObjectName("led_52")
        self.led_53 = QtWidgets.QPushButton(self.frame)
        self.led_53.setGeometry(QtCore.QRect(130, 190, 25, 25))
        self.led_53.setStyleSheet("background-color : white")
        self.led_53.setText("")
        self.led_53.setObjectName("led_53")
        self.led_54 = QtWidgets.QPushButton(self.frame)
        self.led_54.setGeometry(QtCore.QRect(160, 190, 25, 25))
        self.led_54.setStyleSheet("background-color : white")
        self.led_54.setText("")
        self.led_54.setObjectName("led_54")
        self.led_55 = QtWidgets.QPushButton(self.frame)
        self.led_55.setGeometry(QtCore.QRect(190, 190, 25, 25))
        self.led_55.setStyleSheet("background-color : white")
        self.led_55.setText("")
        self.led_55.setObjectName("led_55")
        self.led_56 = QtWidgets.QPushButton(self.frame)
        self.led_56.setGeometry(QtCore.QRect(220, 190, 25, 25))
        self.led_56.setStyleSheet("background-color : white")
        self.led_56.setText("")
        self.led_56.setObjectName("led_56")
        self.led_57 = QtWidgets.QPushButton(self.frame)
        self.led_57.setGeometry(QtCore.QRect(10, 220, 25, 25))
        self.led_57.setStyleSheet("background-color : white")
        self.led_57.setText("")
        self.led_57.setObjectName("led_57")
        self.led_58 = QtWidgets.QPushButton(self.frame)
        self.led_58.setGeometry(QtCore.QRect(40, 220, 25, 25))
        self.led_58.setStyleSheet("background-color : white")
        self.led_58.setText("")
        self.led_58.setObjectName("led_58")
        self.led_59 = QtWidgets.QPushButton(self.frame)
        self.led_59.setGeometry(QtCore.QRect(70, 220, 25, 25))
        self.led_59.setStyleSheet("background-color : white")
        self.led_59.setText("")
        self.led_59.setObjectName("led_59")
        self.led_60 = QtWidgets.QPushButton(self.frame)
        self.led_60.setGeometry(QtCore.QRect(100, 220, 25, 25))
        self.led_60.setStyleSheet("background-color : white")
        self.led_60.setText("")
        self.led_60.setObjectName("led_60")
        self.led_61 = QtWidgets.QPushButton(self.frame)
        self.led_61.setGeometry(QtCore.QRect(130, 220, 25, 25))
        self.led_61.setStyleSheet("background-color : white")
        self.led_61.setText("")
        self.led_61.setObjectName("led_61")
        self.led_62 = QtWidgets.QPushButton(self.frame)
        self.led_62.setGeometry(QtCore.QRect(160, 220, 25, 25))
        self.led_62.setStyleSheet("background-color : white")
        self.led_62.setText("")
        self.led_62.setObjectName("led_62")
        self.led_63 = QtWidgets.QPushButton(self.frame)
        self.led_63.setGeometry(QtCore.QRect(190, 220, 25, 25))
        self.led_63.setStyleSheet("background-color : white")
        self.led_63.setText("")
        self.led_63.setObjectName("led_63")
        self.led_64 = QtWidgets.QPushButton(self.frame)
        self.led_64.setGeometry(QtCore.QRect(220, 220, 25, 25))
        self.led_64.setStyleSheet("background-color : white")
        self.led_64.setText("")
        self.led_64.setObjectName("led_64")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(30, 290, 89, 25))
        self.resetBtn.setObjectName("resetBtn")
        self.generateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.generateBtn.setGeometry(QtCore.QRect(200, 290, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 323, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.initMatrix(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "DOT Matrix Visualizer"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))
        self.generateBtn.setText(_translate("MainWindow", "Generate"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

    def initMatrix(self, MainWindow):
        MainWindow.findChild(QtWidgets.QPushButton,
                             "resetBtn").clicked.connect(self.resetMatrix)
        MainWindow.findChild(QtWidgets.QPushButton,
                             "generateBtn").clicked.connect(self.generateCode)
        self.actionOpen.triggered.connect(self.openCode)
        self.actionExit.triggered.connect(self.quitApp)
        for i in range(1, 65):
            btn = MainWindow.findChild(QtWidgets.QPushButton, "led_" + str(i))
            btn.isClicked = False
            btn.clicked.connect(partial(self.matrixButtonClicked, btn))

    def openCode(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(
            None, "Open File", "", "DOT Matrix Figure (*.dmf)", options=options)
        if fileName:
            f = open(fileName, "r")
            i = 1
            for line in f:
                if(line[0] == ' '):
                    for c in line:
                        if(not c == 'B' and not c == ' ' and not c == ',' and not c == '\n'):
                            btn = MainWindow.findChild(
                                QtWidgets.QPushButton, "led_" + str(i))
                            if(c == '1'):
                                btn.isClicked = True
                                btn.setStyleSheet("background-color : red")
                            else:
                                btn.isClicked = False
                                btn.setStyleSheet("background-color : white")
                            i += 1
            f.close()

    def quitApp(self):
        sys.exit()

    def generateCode(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getSaveFileName(
            None, "Save As", "", "DOT Matrix Figure (*.dmf)", options=options)
        if(fileName):
            out = open(fileName + ".dmf", "w")
            out.write("byte faceName[8] = {\n B")
            c = 0
            for i in range(1, 65):
                btn = MainWindow.findChild(
                    QtWidgets.QPushButton, "led_" + str(i))
                if((i - 1) % 8 == 0 and not (i - 1) == 0):
                    out.write(",\n B")
                if(btn.isClicked):
                    out.write("1")
                else:
                    out.write("0")
            out.write("\n}")
            out.close()

    def resetMatrix(self):
        for i in range(1, 65):
            btn = MainWindow.findChild(QtWidgets.QPushButton, "led_" + str(i))
            btn.isClicked = False
            btn.setStyleSheet("background-color : white")

    def matrixButtonClicked(self, btn):
        if(btn.isClicked):
            btn.setStyleSheet("background-color : white")
        else:
            btn.setStyleSheet("background-color : red")
        btn.isClicked = not btn.isClicked


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
